Fix Jump Latency for Configuration with BTALU
lowRISC/ibex pull request #1203
Opened 2020-11-27 15:12 UTC by ganoam

The jump latency is not affected by the presence of a a branch target
ALU. The pipeline must stall for an instruction fetch from the new
address and flushing the prefetch buffer.

Signed-off-by: ganoam <gnoam@live.com>

2020-11-27 15:19 UTC, ganoam commented
I'm not sure if this is the correct thing to do. I will open an issue instead.

2020-11-27 19:20 UTC, ganoam commented
I think this is correct. The branch target ALU accelerates conditional branches, by computing the branch target and the branch condition in parallel. For unconditional branches, i.e. jumps it makes no difference.

2020-11-30 07:50 UTC, vogelpi requested changes
Hi @ganoam,
thanks for reporting the issue and for doing the PR.

Your fix seems to solve the issue but I fear it's not the right approach. Namely, because it causes a stall cycle in the ID stage for any jump. But this stall is not needed, the ID/EX stage is busy for a single cycle only. There is no other work to be done in ID that would motivate the stalling.

I think the problem you are describing requires a different fix. Probably the `lw` should not enter the ID stage in the first place. By the way, I can't see the `lw` nor the spurious data request in the screenshots you've provided.

I suggest to close this PR, file an issue and upload a wave dump/simple application there to allow us reproducing the problem.

2020-11-30 08:13 UTC, ganoam commented
Alright, I'll do that. Thanks!

2020-11-30 08:13 UTC, closed without merging