[format] Verible formatter experiment v0.0-808-g1e17daa
lowRISC/ibex pull request #1215
Opened 2020-12-16 00:00 UTC by msfschaffner

This is a continuation of the formatter experiment started in https://github.com/lowRISC/ibex/pull/1014.
In particular, the formatter now respects the 2 space indentation rule (https://github.com/google/verible/issues/40) for module parameter and port lists, which should improve things quite a bit.

```shell
$ verible-verilog-format --version
v0.0-808-g1e17daa
Commit	2020-12-14 17:14:57 -0800
Built	2020-12-15T01:35:23Z
```

Invocation (see also https://github.com/lowRISC/opentitan/blob/master/util/verible-format.sh):
```shell
$ verible-verilog-format --formal_parameters_indentation=indent \
                         --named_parameter_indentation=indent \
                         --named_port_indentation=indent \
                         --port_declarations_indentation=indent \
                         --inplace ${filename}
```

If you have a free minute, please go through the diff and highlight up to 3 formatter transformations that you think are horrible and you couldn't live with them being applied to our code base.

The goal here is to get a sense of whether there are any major blockers that should be addressed by the Verible team.

CC @hzeller @fangism @tansell

2020-12-16 11:20 UTC, GregAC commented
Would you mind switching this to a draft PR? As I understand this is not intended to be merged just a way to look at the changes.

Had a quick flick through and it's definitely looking better than last time but I think there's still some room to improve. I'm on holiday from tomorrow so unlikely to have a chance to provide some decent feedback til the new year.

2020-12-17 11:26 UTC, imphil commented on dv/uvm/icache/dv/ibex_icache_ecc_agent/ibex_icache_ecc_monitor.sv
> +class ibex_icache_ecc_monitor extends dv_base_monitor#(
Removing the space in front of `#` feels wrong.

2020-12-17 11:28 UTC, imphil commented on rtl/ibex_core_tracing.sv
> +  );
This line shouldn't get expanded into three.

2021-01-12 21:38 UTC, msfschaffner commented on dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf.sv
> +    input error;
should these get aligned as well?

2021-01-12 21:39 UTC, msfschaffner commented on dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_request_driver.sv
> +class ibex_mem_intf_request_driver extends uvm_driver#(ibex_mem_intf_seq_item);
missing space in front of `#(`

2021-01-12 21:40 UTC, msfschaffner commented on dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_response_driver.sv
> +          ) with {
this looks odd, and I would say `std::randomize(gnt_delay)` should not be wrapped...

2021-01-12 21:43 UTC, msfschaffner commented on dv/uvm/core_ibex/riscv_dv_extension/riscv_core_setting.sv
> +implemented_csr[] = {
is there a reason this is wrapped over three lines? I think this should remain formatted as 
`const privileged_reg_t implemented_csr[] = {\n`

2021-01-12 21:44 UTC, msfschaffner commented on dv/uvm/core_ibex/riscv_dv_extension/riscv_core_setting.sv
> +implemented_csr[] = {
see also instances further below in this file

2021-01-12 21:45 UTC, msfschaffner commented on dv/uvm/icache/dv/env/ibex_icache_env_cfg.sv
> +  constraint clk_freq_50_c {clk_freq_mhz == ClkFreq50Mhz;}
hm... should this be treated like enum or struct definitions?

2021-01-12 21:48 UTC, msfschaffner commented on dv/uvm/icache/dv/ibex_icache_core_agent/seq_lib/ibex_icache_core_back_line_seq.sv
>         req.trans_type == ICacheCoreTransTypeBranch;
this is interesting... is there a reason why the comment is aligned with `req,` above, but all further statements are not?

2021-01-12 21:50 UTC, msfschaffner commented on dv/uvm/icache/dv/ibex_icache_ecc_agent/ibex_icache_ecc_agent_cfg.sv
> +  bit                        error_prob_pc = 10;
this is odd as well. I think this should be formatted as `bit error_prob_pc = 10;`...

2021-01-12 21:58 UTC, msfschaffner commented on rtl/ibex_cs_registers.sv
> +  logic [63:0] mhpmcounter               [32];
I guess this is aligned to the previous group of signal declarations. in order to prevent such alignment, would we have to insert another blank line above before the comment?

2021-01-12 22:02 UTC, udinator commented on dv/uvm/core_ibex/tests/core_ibex_test_lib.sv
> +  virtual task check_mcause(bit irq_or_exc,
would prefer original formatting here, as this line doesn't exceed max length

2021-01-12 22:02 UTC, udinator commented on dv/uvm/core_ibex/tests/core_ibex_test_lib.sv
> +                           1000);
no need to line wrap here

2021-01-12 22:02 UTC, udinator commented on dv/uvm/core_ibex/tests/core_ibex_test_lib.sv
> +    bit                [ 2:0] funct3;
the brackets should not be right-aligned here (and throughout)

2021-01-12 22:02 UTC, udinator commented on dv/uvm/icache/dv/env/ibex_icache_env_cfg.sv
> +  constraint clk_freq_50_c {clk_freq_mhz == ClkFreq50Mhz;}
ideally should keep the original formatting

2021-02-05 02:54 UTC, hzeller commented
Adding @ldalek-antmicro : here an annotated example of Ibex formatting and Verible improvement opportunities. Since you're working on https://github.com/google/verible/pull/643, this will be of interest to you as it highlights problems 'in the field'

2021-06-29 19:46 UTC, martin-lueker requested changes
This is really exciting to see this running.  However it is clear that there are still some styleguide violations in this output.  What is our intent here?  To adapt the styleguide to match verible, or do we want to keep refining this until these formatters are fully styleguide compliant?

2021-06-29 19:46 UTC, martin-lueker commented on dv/uvm/core_ibex/common/irq_agent/irq_monitor.sv
> +      wait(vif.monitor_cb.reset === 1'b0);
This change is a violation of the style guide

2021-06-29 19:46 UTC, martin-lueker commented on dv/uvm/core_ibex/common/irq_agent/irq_monitor.sv
> +        wait(vif.monitor_cb.reset === 1'b1);
ditto.

2021-06-29 19:46 UTC, martin-lueker commented on dv/uvm/core_ibex/common/irq_agent/irq_request_agent.sv
> +  irq_monitor           monitor;
This change is actually preferable!

2021-06-29 19:46 UTC, martin-lueker commented on dv/uvm/core_ibex/common/irq_agent/irq_request_driver.sv
> +class irq_request_driver extends uvm_driver#(irq_seq_item);
Isn't the styleguide explicit about this as well?

2021-06-29 20:00 UTC, msfschaffner commented
> This is really exciting to see this running. However it is clear that there are still some styleguide violations in this output. What is our intent here? To adapt the styleguide to match verible, or do we want to keep refining this until these formatters are fully styleguide compliant?

Hey @martin-lueker. The latter - i.e., the formatter is currently undergoing active refinement, and we are gradually applying it to a growing subset of files in the repository (see for instance https://github.com/lowRISC/opentitan/pull/7125).

Note however that this is an old experimental PR that is completely out of date by now.
Let me close this.

2021-06-29 20:00 UTC, closed without merging