[fcov] Implementing Interrupts section of coverage plan
lowRISC/ibex pull request #1667
Opened 2022-05-24 13:31 UTC by ctopal

Involves documentation changes and elaborated interrupt coverage.

Signed-off-by: Canberk Topal <ctopal@lowrisc.org>

2022-05-24 14:39 UTC, GregAC approved these changes

2022-05-25 15:44 UTC, ctopal commented on dv/uvm/core_ibex/fcov/core_ibex_fcov_if.sv
> +  logic [5:0] fcov_irqs = {id_stage_i.controller_i.irq_nm_ext_i,
I believe that would cause problems with using it in the bin definitions. Consider the case where we see both `NMI_EXTERNAL` and `IRQ_EXTERNAL`, if the bins would be like :

```
bins nmi = irqs.nmi_ext;
bins irq_ext = irqs.irq_ext;
```
We would hit both of them (but in the RTL only process one). So I think keeping this as it is should be fine, what do you think?

2022-05-26 14:22 UTC, GregAC requested changes
Dropping the approve as I've just realised this doesn't quite do what we need.

2022-05-26 14:22 UTC, GregAC commented on dv/uvm/core_ibex/fcov/core_ibex_fcov_if.sv
> +  logic [5:0] fcov_irqs = {id_stage_i.controller_i.irq_nm_ext_i,
Ah yes, I see what you mean.

Though this raises another issue I missed in the first review (and is really down to my poor writing in the coverage plan).

There's two seperate categories here 'interrupt raised' and 'interrupt taken'. For an interrupt to be raised it just means the external system raises the relevant interrupt line. Using a struct as your example above would be find for this as multiple interrupts can be raised together.

However there's also 'interrupt taken'. This is only hit when the core actually chooses to handle the interrupt. You can't work this out purely from the external interrupt lines.

I think the thing to do would be to probe the internal state of `ibex_controller` and when the state is `IRQ_TAKEN` we've just taken an IRQ. You can use the `exc_cause_o` output to work out which bin to put it into.

You could add the struct I've suggested and set the fields based upon looking at `exc_cause_o` then only trigger the relevant cover points when we enter the `IRQ_TAKEN` state.

2022-05-26 14:23 UTC, GregAC commented on dv/uvm/core_ibex/fcov/core_ibex_fcov_if.sv
> +  logic [5:0] fcov_irqs = {id_stage_i.controller_i.irq_nm_ext_i,
Oh and `interrupt raised` as it's own coverage category seems pretty pointless in retrospect. As you cannot have an interrupt taken unless its been raised so `interrupt taken` suffices.

2022-05-30 07:03 UTC, ctopal commented on dv/uvm/core_ibex/fcov/core_ibex_fcov_if.sv
> +  logic [5:0] fcov_irqs = {id_stage_i.controller_i.irq_nm_ext_i,
`fcov_interrupt_taken` is a signal that goes high when we've the next state is `IRQ_TAKEN`. So, that `iff` in the `cp_interrupt_taken` makes sure that we are guaranteeing the state change of the controller to `IRQ_TAKEN`. From there, we are using wildcards to prioritise the incoming interrupts. So with the current code, even if there were two interrupts (let's say `nmi_int` and `nmi_ext`) we would hit only one bin `nmi_external` when we change the state. Do I miss something?

2022-05-30 14:48 UTC, GregAC approved these changes

2022-05-30 14:48 UTC, GregAC commented on dv/uvm/core_ibex/fcov/core_ibex_fcov_if.sv
> +  logic [5:0] fcov_irqs = {id_stage_i.controller_i.irq_nm_ext_i,
Ah yes, you're right, that should work.

2022-05-30 14:56 UTC, merged