[rtl] Do not register instruction fetch errors
lowRISC/ibex pull request #1735
Opened 2022-07-29 16:44 UTC by ctopal

Registering instruction fetch errors causes problem in the case of seeing
a PMP execution access block. ID/EX stage learns about
the instruction that it executed should be blocked a
cycle late. This commit fixes that.

Found this one while working on fixing https://github.com/lowRISC/ibex/issues/1720. However it does not fully solves the issue because we are still seeing some mismatches because of some self modifying code problems.

Signed-off-by: Canberk Topal <ctopal@lowrisc.org>

2022-07-29 17:20 UTC, ctopal commented on rtl/ibex_if_stage.sv
>    assign instr_intg_err_o = instr_intg_err & instr_rvalid_i;
If you have a more optimized way of doing this I would really appreciate the feedback

2022-08-01 11:35 UTC, marnovandermaas approved these changes
LGTM, thanks!

2022-08-02 16:52 UTC, GregAC requested changes
We can't ditch the register stage here. The PC used by the PMP check is from the IF stage. So with change we feed the PMP error of whatever is in the IF stage directly to the ID/EX stage, so we get the PMP check if the PC following the PC we're executing.

The fundamental issue is the timing of PMP register updates. When we have an instruction in ID/EX that writes a PMP register that update gets written to the CSR the same cycle the next instruction moves from IF to ID/EX with it's PMP check done with the old value.

The solution is to flush the pipeline when we get a PMP CSR write. We already have a signal that can do this, `csr_pipe_flush` within `ibex_id_stage`. I think we can just raise it when we have a PMP CSR write.

Alternatively we do nothing. It may acceptable under the specification to say PMP changes aren't guaranteed to take effect until an FLUSH or FLUSH.I, I need to double check the wording. Though as the flush is simple and doesn't cause any other issues I think that's the better option.

2022-08-02 17:06 UTC, GregAC commented
From the spec

> If page-based virtual memory is not implemented, memory accesses check the PMP settings synchronously, so no SFENCE.VMA is needed

I interpret that to mean that PMP CSR writes must take immediate effect (i.e. apply to the next instruction execution) where virtual memory isn't implemented. So we do definitely have to fix this.

2022-08-03 16:33 UTC, ctopal commented
I implemented the solution you suggested, I think it works but need more time to test  it thoroughly.

2022-08-04 09:16 UTC, ctopal commented
I did test the fix in pmp_full_random test, looks like it indeed fixes our problem. @GregAC can you have another look for the new version please?

2022-08-05 08:16 UTC, GregAC approved these changes
LGTM with a couple of small suggestions

2022-08-05 08:16 UTC, GregAC commented on rtl/ibex_id_stage.sv
> +          instr_rdata_i[31:25] == 7'h1D) begin
Try `instr_rdata_i[31:24] == CSR_PMPCFG0[11:5]` makes it more obvious what's going on.

2022-08-05 12:50 UTC, merged