[rtl] Move counter_q definition
lowRISC/ibex pull request #2228
Opened 2024-11-29 19:12 UTC by nasahlpa

The counter_q definition should be outside of the if else such that we have the correct scope. Moreover, Xilinx Vivado reports an error if the DspPragma is a string instead of an int.

2024-11-29 19:18 UTC, nasahlpa commented
Apologies, I should have re-generated the bitstream after addressing this review [comment](https://github.com/lowRISC/ibex/pull/2226#discussion_r1861219466). I assumed this is purely cosmetically but it actually led to a Vivado synthesis failure :/

However, Vivado still gives me the following warning:
`WARNING: [Synth 8-2306] macro COUNTER_FLOP_RST redefined [11464cc7017f312f2c274e572db74bf2/sandbox/linux-sandbox/1586/execroot/_main/bazel-out/k8-fastbuild-ST-9c1027dad682/bin/hw/bitstream/vivado/build.fpga_cw340/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_counter.sv:63]`

Nevertheless, Vivado still seems to create a DSP for a counter with width less than 48-bits, .e.g.: the [mcounters_variable_i](https://github.com/lowRISC/ibex/blob/54985d21b055967c39d0a77b45ae0d573b55b0f7/rtl/ibex_cs_registers.sv#L1380) counter:
![Screenshot from 2024-11-29 20-10-58](https://github.com/user-attachments/assets/1d9939fb-46ac-409e-a16d-2165cb251376)
And for the 64-bit counters no DSP is used, e.g., the [mcycle](https://github.com/lowRISC/ibex/blob/54985d21b055967c39d0a77b45ae0d573b55b0f7/rtl/ibex_cs_registers.sv#L1328) counter:
![Screenshot from 2024-11-29 20-11-14](https://github.com/user-attachments/assets/3808d1ec-39fe-4e86-9b3e-f458d4dfc5d0)

If this warning still is a problem, any ideas @vogelpi or @GregAC how I can rewrite the `COUNTER_FLOP_RST` macro?

2024-12-02 11:56 UTC, vogelpi requested changes
Thanks for fixing this @nasahlpa .

To me it looks like this PR adds a lot more code and makes things much less readable and more complex. It negatively impacts maintenance. I think what we should do:
1. Revert the previous PR which introduced the issue.
2. Do a PR that maybe doesn't address the comment you mentioned but that implements the change without making it much more complex.

2024-12-02 16:57 UTC, nasahlpa commented
As discussed offline:

- I've reverted the previous commit in PR #2229 
- Created two new modules for a Xilinx specific and a general flop implementation that is used in the counters. However, I've decided to not create a dedicated prim for this as we only would use this prim here in Ibex but not in the OpenTitan repository. However, if you think @vogelpi  it would make sense to have this as a dedicated prim I can move it.

2024-12-05 13:40 UTC, vogelpi approved these changes
Thanks @nasahlpa , this is pretty elegant :-)

2024-12-05 13:40 UTC, vogelpi commented on rtl/ibex_counter.sv
> +  localparam string UseDsp = "no";
I think it would be better to use an int type here as well for consistency. Thanks for adding the comment on Vivado requiring `int` instead of `string`.

2024-12-05 13:40 UTC, vogelpi commented on rtl/ibex_counter.sv
> +  generate
Please don't use generate regions, some tools don't support this and this is why our style guide doesn't permit it: https://github.com/lowRISC/style-guides/blob/master/VerilogCodingStyle.md#generate-constructs

2024-12-05 16:26 UTC, nasahlpa commented on rtl/ibex_counter.sv
> +  generate
Fixed, thanks.

2024-12-05 16:26 UTC, nasahlpa commented on rtl/ibex_counter.sv
> +  localparam string UseDsp = "no";
Fixed, thanks.

2024-12-06 09:46 UTC, vogelpi commented
Thanks Pascal for addressing the remaining comments, I think we can merge this today.

2024-12-06 15:13 UTC, merged